[theme]
primaryColor = "#4285F4"  # Google Blue
backgroundColor = "#f5f7ff"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#333333"
font = "sans serif"

[server]
enableStaticServing = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false

[runner]
fastReruns = true